modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="questplaques"
version="${file.jarVersion}"
displayName="Quest Plaques"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/577121"
logoFile="icon.png"
authors="Grend"
description="An addon for Advancement Plaques that adds plaques for quests."

[[dependencies.questplaques]]
	modId="forge"
	mandatory=true
	versionRange="[36,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.questplaques]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.5]"
	ordering="NONE"
	side="BOTH"

[[dependencies.questplaques]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.0.30,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.questplaques]]
	modId="advancementplaques"
	mandatory=true
	versionRange="[1.4.1,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.questplaques]]
	modId="ftbquests"
	mandatory=false
	versionRange="[1605.3.0,)"
	ordering="AFTER"
	side="BOTH"